steps:
- name: Run DeadFinder
  uses: hahwul/deadfinder@1.2.4
  id: broken-link
  with:
    command: sitemap
    target: FACEBOOK.COM

- name: Output Handling
  run: echo '${{ steps.broken-link.outputs.output }}'
